// src/components/community/data.ts
import { Planet, Post } from './types';

export const initialPlanetsData: Planet[] = [
  {
    id: 'earth',
    name: '지구',
    description: '글로벌 커뮤니티 허브, 지역별 게시판 이용 가능',
    color: '#1E88E5',
    position: [0, 0, 0],
    size: 2,
    activeUsers: 2453,
    recentPosts: 178,
    type: 'public',
    topics: ['global', 'community'],
    isPrivate: false,
    stage: 'planet',
    owner: { name: 'System', avatar: null },
    membersCount: 2453,
    lastActivity: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    members: 2453,
    activities: 178,
    health: 100,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 30).toISOString(),
  },
  {
    id: 'techverse',
    name: '테크버스',
    description: '기술 토론, 코딩 도움, 가젯 리뷰',
    color: '#E53935',
    position: [6, 1, -3],
    size: 1.3,
    activeUsers: 982,
    recentPosts: 76,
    type: 'public',
    topics: ['tech', 'code', 'gadgets'],
    isPrivate: false,
    stage: 'planet',
    owner: { name: 'System', avatar: null },
    membersCount: 982,
    lastActivity: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    members: 982,
    activities: 76,
    health: 100,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 10).toISOString(),
  },
  {
    id: 'artsphere',
    name: '아트스피어',
    description: '디지털 및 전통 아티스트를 위한 창조적 예술 커뮤니티',
    color: '#43A047',
    position: [-5, -1, -4],
    size: 1.5,
    activeUsers: 754,
    recentPosts: 92,
    type: 'public',
    topics: ['art', 'design'],
    isPrivate: false,
    stage: 'planet',
    owner: { name: 'System', avatar: null },
    membersCount: 754,
    lastActivity: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
    members: 754,
    activities: 92,
    health: 100,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 15).toISOString(),
  },
  {
    id: 'marketjupiter',
    name: '마켓주피터',
    description: '이커머스 논의, 판매 팁, 시장 트렌드',
    color: '#FB8C00',
    position: [8, -2, 1],
    size: 1.8,
    activeUsers: 534,
    recentPosts: 43,
    type: 'public',
    topics: ['ecommerce', 'business'],
    isPrivate: false,
    stage: 'planet',
    owner: { name: 'System', avatar: null },
    membersCount: 534,
    lastActivity: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    members: 534,
    activities: 43,
    health: 100,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString(),
  },
];

export const initialPosts: Post[] = [
  {
    id: 'post-earth-1',
    planetId: 'earth',
    author: '지구인1',
    authorAvatar: 'https://api.dicebear.com/7.x/pixel-art/svg?seed=earthling1',
    title: '지구 커뮤니티에 오신 것을 환영합니다!',
    content:
      '모두 함께 즐거운 커뮤니티를 만들어가요. 지구의 다양한 소식을 공유해주세요!',
    htmlContent:
      '모두 함께 즐거운 커뮤니티를 만들어가요.<br/>지구의 다양한 소식을 공유해주세요!',
    date: '2023-11-01',
    likes: 15,
    comments: 3,
    tags: ['환영', '공지'],
  },
  {
    id: 'post-tech-1',
    planetId: 'techverse',
    author: '코드마스터',
    authorAvatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=codemaster',
    title: '새로운 React 버전, 어떻게 생각하세요?',
    content:
      '이번에 발표된 React v19에 대한 여러분의 생각을 듣고 싶습니다. 특히 서버 컴포넌트와 액션 기능이 기대되네요.',
    htmlContent:
      '이번에 발표된 React v19에 대한 여러분의 생각을 듣고 싶습니다.<br/>특히 서버 컴포넌트와 액션 기능이 기대되네요.',
    date: '2023-11-02',
    likes: 22,
    comments: 8,
    tags: ['react', 'frontend', 'discussion'],
  },
];
