import { ChatGroup, Message, ActiveMember, ScreenShareData } from './types';

// Mock chat groups data
export const MOCK_CHAT_GROUPS: ChatGroup[] = [
  {
    id: 1,
    name: '피어몰 창업가 모임',
    members: ['창업왕', '디자이너K', '마케팅전문가', '신입몰러'],
    lastMessage: '오늘 세미나 자료 공유해 드립니다.',
    lastMessageTime: '10:30',
    unreadCount: 3,
    avatar: 'https://api.dicebear.com/7.x/shapes/svg?seed=group1',
    type: 'text',
    isActive: true,
  },
  {
    id: 2,
    name: '디지털 아트 크리에이터',
    members: ['일러스트레이터', '3D아티스트', '디자이너K', 'NFT작가'],
    lastMessage: '새 작품에 대한 피드백 부탁드립니다.',
    lastMessageTime: '어제',
    unreadCount: 0,
    avatar: 'https://api.dicebear.com/7.x/shapes/svg?seed=group2',
    type: 'voice',
    isActive: true,
  },
  {
    id: 3,
    name: '한국 수공예품 판매자',
    members: ['도예가', '자수작가', '목공예가', '가죽공예가'],
    lastMessage: '다음 오프라인 전시회 참가 신청하셨나요?',
    lastMessageTime: '어제',
    unreadCount: 0,
    avatar: 'https://api.dicebear.com/7.x/shapes/svg?seed=group3',
    type: 'text',
    isActive: false,
  },
  {
    id: 4,
    name: '콘텐츠 마케팅 전략가',
    members: ['SEO전문가', '카피라이터', '마케팅전문가', '콘텐츠기획자'],
    lastMessage: '요즘 트렌드는 숏폼 콘텐츠입니다. 참고하세요.',
    lastMessageTime: '월요일',
    unreadCount: 0,
    avatar: 'https://api.dicebear.com/7.x/shapes/svg?seed=group4',
    type: 'text',
    isActive: false,
  },
  {
    id: 5,
    name: '웹 개발자 네트워킹',
    members: [
      '프론트엔드개발자',
      '백엔드개발자',
      '디자이너K',
      '프로젝트매니저',
    ],
    lastMessage: '다음 웨비나 주제는 React 18 입니다.',
    lastMessageTime: '화요일',
    unreadCount: 0,
    avatar: 'https://api.dicebear.com/7.x/shapes/svg?seed=group5',
    type: 'video',
    isActive: true,
  },
  {
    id: 6,
    name: '스타트업 투자자 모임',
    members: ['엔젤투자자', 'VC매니저', '스타트업CEO', '인큐베이터매니저'],
    lastMessage: '다음 피칭 세션은 언제인가요?',
    lastMessageTime: '수요일',
    unreadCount: 0,
    avatar: 'https://api.dicebear.com/7.x/shapes/svg?seed=group6',
    type: 'video',
    isActive: false,
  },
];

// Mock messages for active chat
export const MOCK_MESSAGES: Message[] = [
  {
    id: 1,
    sender: '창업왕',
    content: '여러분 안녕하세요! 오늘 세미나에 참석해주셔서 감사합니다.',
    time: '10:15',
    avatar: 'https://api.dicebear.com/7.x/personas/svg?seed=user1',
    isMe: false,
  },
  {
    id: 2,
    sender: '디자이너K',
    content: '좋은 정보 감사합니다. 발표자료도 공유해주실 수 있을까요?',
    time: '10:18',
    avatar: 'https://api.dicebear.com/7.x/personas/svg?seed=user2',
    isMe: false,
  },
  {
    id: 3,
    sender: '창업왕',
    content: '네, 물론이죠! 세미나 자료 공유해드립니다.',
    time: '10:20',
    avatar: 'https://api.dicebear.com/7.x/personas/svg?seed=user1',
    isMe: false,
  },
  {
    id: 4,
    sender: '마케팅전문가',
    content: '정말 유익한 시간이었습니다. 다음 세미나도 기대할게요.',
    time: '10:23',
    avatar: 'https://api.dicebear.com/7.x/personas/svg?seed=user3',
    isMe: false,
  },
  {
    id: 5,
    sender: '신입몰러',
    content:
      '처음 참여했는데 많은 도움이 되었어요! 다음에도 참여하고 싶습니다.',
    time: '10:25',
    avatar: 'https://api.dicebear.com/7.x/personas/svg?seed=user4',
    isMe: false,
  },
  {
    id: 6,
    sender: '창업왕',
    content:
      "다음 세미나는 '피어몰 매출 증대를 위한 SNS 마케팅 전략'을 주제로 진행할 예정입니다. 많은 참여 부탁드립니다!",
    time: '10:28',
    avatar: 'https://api.dicebear.com/7.x/personas/svg?seed=user1',
    isMe: false,
  },
  {
    id: 7,
    sender: '창업왕',
    content: '오늘 세미나 자료 공유해 드립니다.',
    time: '10:30',
    avatar: 'https://api.dicebear.com/7.x/personas/svg?seed=user1',
    isMe: false,
  },
  {
    id: 8,
    sender: '익명 사용자',
    content: '감사합니다! 잘 보겠습니다.',
    time: '10:32',
    avatar: '',
    isMe: true,
  },
];

// Mock active members
export const ACTIVE_MEMBERS: ActiveMember[] = [
  {
    id: 1,
    name: '창업왕',
    status: 'online',
    avatar: 'https://api.dicebear.com/7.x/personas/svg?seed=user1',
    isSpeaking: false,
    isHost: true,
    isMuted: false,
  },
  {
    id: 2,
    name: '디자이너K',
    status: 'online',
    avatar: 'https://api.dicebear.com/7.x/personas/svg?seed=user2',
    isSpeaking: true,
    isHost: false,
    isMuted: true,
  },
  {
    id: 3,
    name: '마케팅전문가',
    status: 'away',
    avatar: 'https://api.dicebear.com/7.x/personas/svg?seed=user3',
    isSpeaking: false,
    isHost: false,
    isMuted: true,
  },
  {
    id: 4,
    name: '신입몰러',
    status: 'offline',
    avatar: 'https://api.dicebear.com/7.x/personas/svg?seed=user4',
    isSpeaking: false,
    isHost: false,
    isMuted: false,
  },
  {
    id: 5,
    name: '프로젝트매니저',
    status: 'online',
    avatar: 'https://api.dicebear.com/7.x/personas/svg?seed=user5',
    isSpeaking: false,
    isHost: false,
    isMuted: true,
  },
  {
    id: 6,
    name: '백엔드개발자',
    status: 'online',
    avatar: 'https://api.dicebear.com/7.x/personas/svg?seed=user6',
    isSpeaking: false,
    isHost: false,
    isMuted: false,
  },
];

// Mock screen shares
export const SCREEN_SHARES: ScreenShareData[] = [
  {
    id: 1,
    userId: 1,
    name: '프레젠테이션',
    type: 'screen',
  },
  {
    id: 2,
    userId: 2,
    name: '브라우저 창',
    type: 'window',
  },
  {
    id: 3,
    userId: 1,
    name: '전체 화면',
    type: 'screen',
  },
];
